### ISSUE TITLE
Implementing on LiveUSB

### ISSUE THREAD

**Issue by sevagh** [bgw/bdw-ucode-update-tool#3]
Hey,

If you recall I was able to (with the help of this repo) get Fedora 22 to work stably with the 0x13 microcode.

A few hours ago I bricked my Fedora install (some /usr/lib 32/64-bit symlinking mistakes) and now I can't get Fedora 23 on a LiveUSB to be stable, due to the microcode (grep microcode /proc/cpuinfo shows the bad microcode, 0x10).

ASRock, my manufacturer, has not made any BIOS updates since mid-2015.

Any tips on how I could get a LiveUSB patched with the good microcode?

**Comment by sevagh** [comment]
Actually I just tried booting and downloading this repo over and over (to run install.sh) until finally it stayed stable long enough to install it, so problem solved for now.

Still disappointing from ASRock

**Comment by bgw** [comment]
Hi @sevagh, I'm not sure how you could add it to the LiveUSB image, but it looks like Fedora does have a new-ish microcode_ctl package that you can install, and it looks like it includes the official late-2015 microcode updates released by Intel that fixes these problems. You may want to switch to that, instead of using this repository.

**Comment by sevagh** [comment]
In fact I ran "dnf upgrade microcode_ctl" and it downloaded an update but it didn't change my microcode. Not sure if I'm using it incorrectly.

**Comment by bgw** [comment]
Ah. It may only update the microcode on reboot, but that's not very useful for a live usb image.
